# commnets
: <<'END'
    Single GPU 든 Multi GPU 든 Batch size는 같아야 합니다! 그래야 정확한 비교가 됩니다!
    ( 대신 workers = (num_gpu) * workers )

    < Single Gpu Arguments >
    --gpu 0                                 # gpu number
    --dataset Task004_AVT_thickness1.5      # task name
    --model resunet                         # 
    --batch_size 4                          # 1~8
    --num_workers 8                         # 4 or 8
    --amp                                   # Automatic mixed precision     !!!!!!!!!!!!!왠만하면 amp 모드로 실행해 주세요!!!!!!!!!!
    --fold_num 0                            # fold number



    < Multi Gpu Arguments >
    --gpu 0,1,2,3                           # gpu numbers
    --dataset Task004_AVT_thickness1.5      # task name
    --model resunet                         # 
    --batch_size 4                          # 1~8
    --num_workers 32                        # 4 or 8   x  (num_gpu)
    --amp                                   # Automatic mixed precision  
    --fold_num 0                            # fold number
END



# export OPENBLAS_NUM_THREADS=1 # multiprocessing에서 2개 이상의 코어 사용하지 않게 하는 코드
# export OMP_NUM_THREADS=1

# >> Original Image
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18' --activationF 'softmax' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-10-06:01/checkpoint_0923.pth.tar' # AUC 0.7966 | ACC 0.6429
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18' --activationF 'sigmoid' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-10-06:01/checkpoint_0923.pth.tar' # AUC 0.8931 | ACC 0.6429
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18' --activationF 'sigmoid' --cancerstageTest '12' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-10-06:01/checkpoint_0923.pth.tar' # AUC 0.7762 | ACC 0.7024
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18' --activationF 'sigmoid' --cancerstageTest '34' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-10-06:01/checkpoint_0923.pth.tar' # AUC 0.9219 | ACC 0.7024
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18' --activationF 'sigmoid' --cancerstageTest '1234' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-10-06:01/checkpoint_0923.pth.tar' # AUC 0.7929 | ACC 0.7024
# >> concat[Original Image, Segmentation Mask]
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'softmax' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-07-10:10/checkpoint_0629.pth.tar' # AUC 0.7110 | ACC 0.7820
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'sigmoid' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-07-10:10/checkpoint_0629.pth.tar' # AUC 0.7202 | ACC 0.7820
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'softmax' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-07-10:10/checkpoint_0481.pth.tar' # AUC 0.6092 | ACC 0.7331
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'sigmoid' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-07-10:10/checkpoint_0481.pth.tar' # AUC 0.6773 | ACC 0.7331
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'softmax' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-14-10:14/checkpoint_0722.pth.tar' # AUC 0.7384 | ACC 0.7218
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'sigmoid' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-14-10:14/checkpoint_0722.pth.tar' # AUC 0.7272 | ACC 0.7218
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'sigmoid' --cancerstageTest '12' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-14-10:14/checkpoint_0722.pth.tar' # AUC 0.7272 | ACC 0.7218
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'sigmoid' --cancerstageTest '34' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-14-10:14/checkpoint_0722.pth.tar' # AUC 0.7272 | ACC 0.7218
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --tumorCrop 0 --model 'resnetMC3_18_wMask' --activationF 'sigmoid' --cancerstageTest '1234' --test_pth '/mnt/KW/LungCancer/CT/results/SavedModels/resnetMC3_18_wMask/X(2.0)Y(2.0)Z(2.5)/whole/tr(1234)/2023-11-14-10:14/checkpoint_0722.pth.tar' # AUC 0.7272 | ACC 0.7218

# >> Pathology + C.Info
# python test_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --modality [\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --tumorCrop 0 --model_CT 'resnetMC3_18' --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/modality(23)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2023-12-07-04:46/checkpoint_0552.pth.tar' # AUC | ACC


# python test_ddp.py --gpu 4,5,6,7 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --modality [\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --tumorCrop 0 --model_CT 'resnetMC3_18' --cos --lr 0.0001 --clinical_features [\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/modality(3)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2023-12-22-00:46:26/checkpoint_0999.pth.tar'
# python test_ddp.py --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/modality(23)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-02-05:10:59/checkpoint_0999.pth.tar' # 292,750,999
# python test_ddp.py --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/modality(123)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-03-02:37:29/checkpoint_0335.pth.tar'
# python test_ddp.py --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 4,5,6,7 --multiprocessing_distributed --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/modality(12)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-04-05:12:44/checkpoint_0999.pth.tar'
# python test_ddp.py --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 4,5,6,7 --multiprocessing_distributed --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/modality(2)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-08-06:42:25/checkpoint_0610.pth.tar'
# python test_ddp.py --hospital_test [\'AJMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 4,5,6,7 --multiprocessing_distributed --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/AJMC/modality(1)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-09-10:53:13/checkpoint_0962.pth.tar' #815
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 4,5,6,7 --multiprocessing_distributed --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-11-11:59:42/checkpoint_0353.pth.tar' # 353, 525, 018
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,4,5,6,7 --multiprocessing_distributed --cos --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-12-04:14:37/checkpoint_0942.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,4,5,6,7 --multiprocessing_distributed --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(123)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-13-08:10:26/checkpoint_0997.pth.tar' # 620, 997
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,4,5,6,7 --multiprocessing_distributed --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-15-07:18:06/checkpoint_0059.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,4,5,6,7 --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-15-09:28:43/checkpoint_0014.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --pretrainedExt_CT 1 --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-15-09:28:43/checkpoint_0014.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(123)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-15-16:39:27/checkpoint_0016.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(123)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-15-17:33:30/checkpoint_0012.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(123)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-16-04:38:34/checkpoint_0330.pth.tar' # 330
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(123)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-17-10:53:19/checkpoint_0838.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\'] --cancerstageTrain '1234' --cancerstageTest '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-18-01:32:43/checkpoint_0034.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CI\'] --model_CI 'simpleFCs_v2' --cancerstageTrain '1234' --cancerstageTest '1234' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-19-09:07:57/checkpoint_0756.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'TransMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-20-08:03:20/checkpoint_0286.pth.tar' # 286
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\'] --model_CT 'resnetMC3_18' --cancerstageTrain '1234' --cancerstageTest '1234' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/norm_[2.0,2.0,2.5]/mask(X)/crop(whole)/resnetMC3_18/2024-01-21-01:12:49/checkpoint_0016.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CI\'] --model_CI 'simpleFCs_v3' --cancerstageTrain '1234' --cancerstageTest '1234' --gpu 4,5 --multiprocessing_distributed --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-24-05:10:50/checkpoint_0475.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'ABMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 3 --gpu 5,6,7 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/ABMIL/norm_[2.0,2.0,2.5]/2024-01-25-08:45:38/checkpoint_0488.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'ABMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 3 --gpu 0,2,3 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/ABMIL/norm_[2.0,2.0,2.5]/2024-01-30-09:16:14/checkpoint_0002.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'ABMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 3 --gpu 0,2,3 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/ABMIL/norm_[2.0,2.0,2.5]/2024-01-30-09:44:15/checkpoint_0001.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'ABMIL_v2' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 3 --gpu 0,2,3 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/ABMIL_v2/norm_[2.0,2.0,2.5]/2024-01-30-14:07:36/checkpoint_0009.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CI\'] --model_pathology 'simpleFCs_v2' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 3 --gpu 0,2,3 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-19-09:07:57/checkpoint_0756.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CI\'] --model_CI 'simpleFCs_v2' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2/norm_[2.0,2.0,2.5]/2024-01-31-07:27:00/checkpoint_0473.pth.tar'
# python test_ddp.py --label '5yOS' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\',\'CI\'] --model_pathology 'ABMIL_v2' --model_CI 'simpleFCs_v2' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(23)/stage_tr(1234)/ABMIL_v2-simpleFCs_v2/norm_[2.0,2.0,2.5]/2024-01-31-13:35:53/checkpoint_0843.pth.tar'
# python test_ddp.py --label '5yOS' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\',\'CI\'] --model_pathology 'ABMIL_v2' --model_CI 'simpleFCs_v2' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(23)/stage_tr(1234)/ABMIL_v2-simpleFCs_v2/norm_[2.0,2.0,2.5]/2024-02-01-07:45:48/checkpoint_0208.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\',\'CI\'] --data_integration 1 --model_pathology 'ABMIL' --model_CI 'CLIP' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(23)/stage_tr(1234)/ABMIL-CLIP/norm_[2.0,2.0,2.5]/2024-02-02-08:21:17/checkpoint_0034.pth.tar'
# python test_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --data_integration 1 --model_pathology 'TransMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/TransMIL/norm_[2.0,2.0,2.5]/2024-02-02-12:51:17/checkpoint_0006.pth.tar'
# python test_ddp_clip.py --loss 'BCE+CLIP' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'TransMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/TransMIL/norm_[2.0,2.0,2.5]/2024-02-07-07:48:11/checkpoint_0443.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --data_integration 0 --model_pathology 'TransMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/TransMIL/norm_[2.0,2.0,2.5]/2024-02-14-10:58:20/checkpoint_0018.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --data_integration 1 --model_pathology 'TransMIL' --cancerstageTrain '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/TransMIL/norm_[2.0,2.0,2.5]/2024-02-14-11:22:25/checkpoint_0009.pth.tar'
# python test_ddp.py --label 'classification_cancer' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --data_integration 1 --model_pathology 'TransMIL' --cancerstageTrain '1234' --cancerstageTest '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/TransMIL/norm_[2.0,2.0,2.5]/2024-02-15-05:29:11/checkpoint_0449.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'pathology\'] --data_integration 0 --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/TransMIL/norm_[0.6869,0.6869,3.0]/2024-02-19-07:51:19/checkpoint_0091.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'pathology\'] --data_integration 0 --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --batch_size 4 --gpu 0,1,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(2)/stage_tr(1234)/TransMIL/norm_[0.6869,0.6869,3.0]/2024-02-19-18:15:27/checkpoint_0005.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\'] --data_integration 0 --model_CT 'resnetMC3_18' --pretrainedExt_CT 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-20-04:15:45/checkpoint_0111.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\'] --data_integration 0 --model_CT 'medicalNet' --pretrainedExt_CT 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/medicalNet/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-21-05:32:08/checkpoint_0008.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\'] --data_integration 0 --model_CT 'resnetMC3_18' --pretrainedExt_CT 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-22-01:28:56/checkpoint_0099.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-22-17:42:37/checkpoint_0091.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-23-03:03:36/checkpoint_0318.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-26-14:47:59/checkpoint_0104.pth.tar'
# python test_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'ABMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(ABMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-29-06:32:22/checkpoint_best.pth.tar'
# python test_ddp.py --mode 'test' --best_thres 0.9336 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-03-15:03:36/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.5280 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-12-07:27:28/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.7706 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-12-07:26:10/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.8097 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-12-17:07:23/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.7414 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-12-16:53:23/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 1 --mode 'test' --best_thres 0.5020 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-00:26:13/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 1 --mode 'test' --best_thres 0.6371 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-00:26:23/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 1 --mode 'test' --best_thres 0.7070 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-01:39:16/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 1 --mode 'test' --best_thres 0.4188 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-01:39:32/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 2 --mode 'test' --best_thres 0.4510 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-05:01:36/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 2 --mode 'test' --best_thres 0.5610 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-05:01:50/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 2 --mode 'test' --best_thres 0.3814 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-05:02:07/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 2 --mode 'test' --best_thres 0.3984 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-05:02:28/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 3 --mode 'test' --best_thres 0.4441 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-07:08:57/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 3 --mode 'test' --best_thres 0.5205 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v1' --model_CI 'simpleFCs_v1d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v1d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-07:09:09/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 3 --mode 'test' --best_thres 0.5762 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-07:09:20/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 3 --mode 'test' --best_thres 0.2212 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/simpleFCs_v2d(TransMIL)/norm_[0.6869,0.6869,3.0]/2024-03-13-07:09:34/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9229 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 2,3 --num_workers 8 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/CLIP(TransMIL)/norm_[0.6869,0.6869,3.0]/[0]2024-03-18-08:12:07/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 1 --mode 'test' --best_thres 0.8971 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 2,3 --num_workers 8 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.0001 --test_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(3)/stage_tr(1234)/CLIP(TransMIL)/norm_[0.6869,0.6869,3.0]/[1]2024-03-18-08:13:25/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9846 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'v2' --model_CI 'simpleFCs_v2d' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-18-06:28:33/checkpoint_best.pth.tar'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9890 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL_seperate' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL_seperate)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-20-03:24:58'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9329 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL_seperate' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL_seperate)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-20-03:38:39'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.4544 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-22-06:10:58'
# python train_ddp2.py --val_fold 0 --label '5yOS' --loss 'BCE+textCosSim' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --save_best
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.6783 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.0001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-25-01:11:21'
python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.4430 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 0,1 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-25-08:03:10'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.5997 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-25-12:53:21'
# python test_ddp.py --val_fold 1 --mode 'test' --best_thres 0.5491 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[1]2024-03-26-06:18:08'
# python test_ddp.py --val_fold 1 --mode 'test' --best_thres 0.6909 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[1]2024-03-26-06:19:46'
# python test_ddp.py --val_fold 2 --mode 'test' --best_thres 0.5544 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[2]2024-03-29-05:57:29'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.4424 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 2,3 --num_workers 8 --dist_url 'tcp://localhost:4450' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-03-31-09:15:25'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.5225 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-01-07:41:33'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.6055 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 0,1,2,3 --num_workers 8 --dist_url 'tcp://localhost:4447' --multiprocessing_distributed --lr 0.001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-03-07:07:46'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.6805 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 0,1,2,3 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-04-03:01:28'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.4950 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 3 --gpu 0,1,4 --num_workers 6 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-05-01:14:23'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.6011 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL_per_modality' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL_per_modality)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-11-06:17:52'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.7714 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL_per_modality' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL_per_modality)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-11-05:01:52'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.5226 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-12-09:20:39'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9716 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CT' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-29-06:35:52'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9172 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-29-07:10:38'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.5220 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-30-02:19:33'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.3501 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-04-30-08:20:49'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9860 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'single' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-05-01-08:00:39'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.7068 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'devided' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-05-01-07:53:28'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9373 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'single' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-05-02-07:11:34'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9937 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'devided' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-05-02-07:13:04'
# python test_ddp.py --val_fold 0 --mode 'test' --best_thres 0.9882 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'single' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36'
# python test_ddp.py --val_fold 0 --mode 'valid' --best_thres 0.5 --label 'locationcancer' --num_classes 5 --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\'] --alignment_base 'none' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'single' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_freeze 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --test_pth 'EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-05-10-10:12:03'