# commnets
: <<'END'
    Single GPU 든 Multi GPU 든 Batch size는 같아야 합니다! 그래야 정확한 비교가 됩니다!
    ( 대신 workers = (num_gpu) * workers )

    < Single Gpu Arguments >
    --gpu 0                                 # gpu number
    --dataset Task004_AVT_thickness1.5      # task name
    --model resunet                         # 
    --batch_size 4                          # 1~8
    --num_workers 8                         # 4 or 8
    --amp                                   # Automatic mixed precision     !!!!!!!!!!!!!왠만하면 amp 모드로 실행해 주세요!!!!!!!!!!
    --fold_num 0                            # fold number



    < Multi Gpu Arguments >
    --gpu 0,1,2,3                           # gpu numbers
    --dataset Task004_AVT_thickness1.5      # task name
    --model resunet                         # 
    --batch_size 4                          # 1~8
    --num_workers 32                        # 4 or 8   x  (num_gpu)
    --amp                                   # Automatic mixed precision  
    --fold_num 0                            # fold number
END



# export OPENBLAS_NUM_THREADS=1 # multiprocessing에서 2개 이상의 코어 사용하지 않게 하는 코드
# export OMP_NUM_THREADS=1
export CUDA_LAUNCH_BLOCKING=1

# python train_ddp.py --gpu 4,5,6,7 --multiprocessing_distributed --modality [\'pathology\',\'CI\'] --cancerstageTrain '1234' --tumorCrop 0 --model_CT 'resnetMC3_18' --cos
# python train_ddp.py --gpu 4,5 --multiprocessing_distributed --modality [\'pathology\'] --cancerstageTrain '1234' --tumorCrop 0 --model_CT 'resnetMC3_18' --cos
# python train_ddp.py --gpu 6,7 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --modality [\'CI\'] --cancerstageTrain '1234' --tumorCrop 0 --model_CT 'resnetMC3_18' --cos
# python train_ddp.py --gpu 4,5,6,7 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --modality [\'CI\'] --cancerstageTrain '1234' --cos --lr 0.0001 --clinical_features [\'sex\',\'age\',\'sm\',\'initialdate\',\'treatedate\',\'relapse\',\'lastdate\']
# python train_ddp.py --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --pretrainedExt_pathology 0 --cancerstageTrain '1234' --model_CT 'resnetMC3_18' --gpu 4,5,6,7 --multiprocessing_distributed --cos --resume '/mnt/KW/LungCancer/Multimodality/results/SavedModels/modality(2)/stage_tr(1234)/norm_[2.0,2.0,2.5]/2024-01-08-05:20:43/checkpoint_0191.pth.tar'
# python train_ddp.py --hospital_test [\'AJMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\'] --pretrainedExt_pathology 0 --cancerstageTrain '1234' --model_CT 'resnetMC3_18' --gpu 4,5,6,7 --multiprocessing_distributed --cos
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\'] --pretrainedExt_CT 1 --pretrainedExt_pathology 1 --cancerstageTrain '1234' --model_CT 'resnetMC3_18' --gpu 0,1,4,5,6,7 --multiprocessing_distributed --cos
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\',\'CI\'] --pretrainedExt_CT 1 --pretrainedExt_pathology 1 --pretrainedExt_CI 1 --pretrainedExt_freeze 1 --cancerstageTrain '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\',\'pathology\'] --pretrainedExt_CT 1 --pretrainedExt_pathology 1 --pretrainedExt_freeze 0 --cancerstageTrain '1234' --model_CT 'resnetMC3_18' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CI\'] --model_CI 'simpleFCs_v2' --pretrainedExt_CI 0 --cancerstageTrain '1234' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\'] --model_CT 'resnetMC3_18' --pretrainedExt_CT 0 --cancerstageTrain '1234' --gpu 0,1,2,3,4,5,6,7 --multiprocessing_distributed --lr 0.00001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CT\'] --model_CT 'MViT' --pretrainedExt_CT 0 --cancerstageTrain '1234' --gpu 4,5 --batch_size 2 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --cancerstageTrain '1234' --gpu 5,6,7 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'ABMIL' --pretrainedExt_pathology 0 --cancerstageTrain '1234' --batch_size 3 --gpu 5,6,7 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'ABMIL_v2' --pretrainedExt_pathology 0 --cancerstageTrain '1234' --batch_size 3 --gpu 0,2,3 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'CI\'] --model_CI 'simpleFCs_v2' --pretrainedExt_CI 0 --cancerstageTrain '1234' --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\',\'CI\'] --model_pathology 'ABMIL_v2' --pretrainedExt_pathology 1 --model_CI 'simpleFCs_v2' --pretrainedExt_CI 1 --cancerstageTrain '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\',\'CI\'] --data_integration 1 --model_pathology 'ABMIL' --pretrainedExt_pathology 0 --model_CI 'CLIP' --pretrainedExt_CI 0 --cancerstageTrain '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --data_integration 1 --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --cancerstageTrain '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp_clip.py --loss 'BCE+CLIP' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'classification_cancer\'] --modality [\'pathology\'] --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --cancerstageTrain '1234' --batch_size 40 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --label 'classification_cancer' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --data_integration 1 --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --cancerstageTrain '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --tumorCrop 0 --clinical_features [\'sex\',\'age\',\'sm\',\'locationcancer\',\'cancerimaging\',\'cancerimagingT\',\'cancerimagingN\',\'cancerimagingM\',\'classification_cancer\'] --modality [\'pathology\'] --data_integration 1 --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --cancerstageTrain '1234' --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'pathology\'] --data_integration 0 --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'pathology\'] --data_integration 0 --model_pathology 'TransMIL' --pretrainedExt_pathology 0 --batch_size 4 --gpu 0,1,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001
# python train_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\'] --data_integration 0 --model_CT 'resnetMC3_18' --pretrainedExt_CT 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001
# python train_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 32 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --resume '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-22-17:42:37/checkpoint_0150.pth.tar'
# python train_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'ABMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best --resume 'LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(ABMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-02-28-17:43:53/checkpoint_0142.pth.tar'
# python train_ddp.py --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 0,1 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --save_best
# python train_ddp.py --val_fold 1 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 2,3 --num_workers 8 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.0001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.0001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CI\'] --data_integration 0 --CI_input_version 'v2' --model_CI 'simpleFCs_v2d' --aggregator 'TransMIL' --pretrainedExt_CI 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4447' --multiprocessing_distributed --lr 0.0001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL_seperate' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE+textCosSim' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.0001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 2,3 --num_workers 8 --dist_url 'tcp://localhost:4446' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 0 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 4,5,6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 4,5,6,7 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 0,1,2,3 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL_per_modality' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 4 --gpu 0,1,2,3 --num_workers 16 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 1 --batch_size 4 --gpu 4,5,6,7 --num_workers 16 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CT' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 6,7 --num_workers 8 --dist_url 'tcp://localhost:4445' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'devided' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best
# python train_ddp.py --val_fold 0 --label '5yOS' --loss 'BCE' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'devided' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/2024-03-05-00:18:36/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 2 --gpu 4,5 --num_workers 8 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.00001 --save_best --resume 'EUMC+HUMC+SCHMC/modality(12)/stage_tr(1234)/resnetMC3_18-TransMIL(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-05-01-00:57:46'
python train_ddp.py --val_fold 0 --label '5yOS' --num_classes 2 --loss 'BCE' --loss_point 'CT-Pth-Last' --hospital_test [\'EUMC\',\'HUMC\',\'SCHMC\'] --modality [\'CT\',\'pathology\'] --alignment_base 'CI' --data_integration 0 --model_CT 'resnetMC3_18' --model_pathology 'TransMIL' --CI_input_version 'text' --CI_prompt_version 'single' --model_CI 'CLIP' --aggregator 'TransMIL' --pretrainedExt_CT 1 --pretrainedExt_CT_pth '/mnt/KW/LungCancer/Multimodality2/results/SavedModels/EUMC+HUMC+SCHMC/modality(1)/stage_tr(1234)/resnetMC3_18(TransMIL)/norm_[0.6869,0.6869,3.0]/mask(X)/crop(X)/[0]2024-05-10-10:12:03/checkpoint_best.pth.tar' --pretrainedExt_freeze 1 --pretrainedExt_pathology 0 --pretrainedExt_CI 0 --learnablePrompt 0 --batch_size 3 --gpu 4,6,7 --num_workers 12 --dist_url 'tcp://localhost:4444' --multiprocessing_distributed --lr 0.0001 --save_best